### ISSUE TITLE
ruby2.0.full

### ISSUE THREAD

**Issue by whomwah** [brightbox/deb-ruby2.0#2]
Hi,

The 1.9.1 packages had a ruby1.9.1-full which you would use to install everything. It was helpful because it installed the headers too. Does 2.0 have similar as I'm finding that:

`apt-get install ruby2.0`

just installs the ruby2.0 package and not the headers. Or should I be using something else?

ta,
D

**Comment by johnl** [comment]
I'm following upstream Debian as much as I can and they just don't provide the -full packages any more, so neither am I.
