### ISSUE TITLE
installing ruby with rails I may be missing some packages

### ISSUE THREAD

**Issue by gartha1** [brightbox/deb-ruby2.0#4]
I just tried to install Ruby with
https://gist.github.com/anonymous/40d15e7e1f7587409de6
sudo apt-add-repository ppa:brightbox/ruby-ng-experimental &&
sudo apt-get update &&
sudo apt-get install -y ruby2.0 ruby2.0-dev ruby2.0-doc

I know you have to install ruby2.0-dev before rails.. I did that.. but still got an error trying [sudo] gem install rails

sudo gem install 
but that said 
ERROR:  Error installing rails:
  ERROR: Failed to build gem native extension.

rails -v said

The program 'rails' can be found in the following packages:
 * ruby-railties-3.2
 * ruby-railties-4.0
Try: sudo apt-get install <selected package>

should I have done apt-get install ruby-full to get ruby-railties.. ?  But then since apt-get install ruby-full in ubuntu only gets Ruby 1.9.1, how would I do it for Ruby 2.0?  

I have read of doing apt-get install Ruby2.0-dev    I did that.

sudo gem install rails, said

    /usr/bin/ruby2.0 extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

I could try what rails -v suggested..
installing
 * ruby-railties-3.2
 * ruby-railties-4.0

But then I wonder what other packages I am missing

**Comment by johnl** [comment]
here you need the libxml2-dev and libxslt-dev packages, which are needed for nokogiri to compile.

the ruby-railties stuff is a red herring (nobody uses the apt packages for rails :)

so this isn't a bug in these packages, so closing this ticket. But if you need any more help, try the mailing list.
